/**
 * Catálogo de Tipos de Movimentação — metadados de persistência/projeção.
 *
 * Sprint 2.2: fonte única de metadados — sem execução de regra de negócio.
 *
 * @module motores/motor-comercial/config/comercialTiposMovimentacao
 */

const LEDGER = Object.freeze({
  CONSIGNACAO: 'CONSIGNACAO',
  PERFIL: 'PERFIL'
});

const TIPOS_LEDGER_CONSIGNACAO = Object.freeze({
  ENTREGA: {
    codigo: 'ENTREGA',
    ledger: LEDGER.CONSIGNACAO,
    afetaFinanceiro: false,
    afetaEstoque: true,
    afetaLimite: true,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: true,
    geraIndicador: true,
    geraNotificacao: true,
    permiteCancelamento: true,
    permiteEstorno: false,
    exigeAutorizacao: false,
    exigeSnapshot: false
  },
  DEVOLUCAO: {
    codigo: 'DEVOLUCAO',
    ledger: LEDGER.CONSIGNACAO,
    afetaFinanceiro: false,
    afetaEstoque: true,
    afetaLimite: true,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: true,
    geraIndicador: true,
    geraNotificacao: false,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: false,
    exigeSnapshot: false
  },
  ABERTURA_PRESTACAO: {
    codigo: 'ABERTURA_PRESTACAO',
    ledger: LEDGER.CONSIGNACAO,
    afetaFinanceiro: false,
    afetaEstoque: false,
    afetaLimite: false,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: false,
    geraIndicador: false,
    geraNotificacao: true,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: false,
    exigeSnapshot: false
  },
  VENDA_PRESTACAO: {
    codigo: 'VENDA_PRESTACAO',
    ledger: LEDGER.CONSIGNACAO,
    afetaFinanceiro: true,
    afetaEstoque: false,
    afetaLimite: true,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: true,
    geraIndicador: true,
    geraNotificacao: false,
    permiteCancelamento: false,
    permiteEstorno: true,
    exigeAutorizacao: false,
    exigeSnapshot: false
  },
  PERDA: {
    codigo: 'PERDA',
    ledger: LEDGER.CONSIGNACAO,
    afetaFinanceiro: false,
    afetaEstoque: false,
    afetaLimite: false,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: true,
    geraIndicador: true,
    geraNotificacao: true,
    permiteCancelamento: false,
    permiteEstorno: true,
    exigeAutorizacao: false,
    exigeSnapshot: false
  },
  CORTESIA: {
    codigo: 'CORTESIA',
    ledger: LEDGER.CONSIGNACAO,
    afetaFinanceiro: false,
    afetaEstoque: false,
    afetaLimite: false,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: true,
    geraIndicador: true,
    geraNotificacao: false,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: false,
    exigeSnapshot: false
  },
  FECHAMENTO_PRESTACAO: {
    codigo: 'FECHAMENTO_PRESTACAO',
    ledger: LEDGER.CONSIGNACAO,
    afetaFinanceiro: true,
    afetaEstoque: false,
    afetaLimite: true,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: true,
    geraIndicador: true,
    geraNotificacao: true,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: false,
    exigeSnapshot: true
  },
  PAGAMENTO: {
    codigo: 'PAGAMENTO',
    ledger: LEDGER.CONSIGNACAO,
    afetaFinanceiro: true,
    afetaEstoque: false,
    afetaLimite: true,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: true,
    geraIndicador: true,
    geraNotificacao: true,
    permiteCancelamento: false,
    permiteEstorno: true,
    exigeAutorizacao: false,
    exigeSnapshot: false
  },
  AJUSTE_VALOR: {
    codigo: 'AJUSTE_VALOR',
    ledger: LEDGER.CONSIGNACAO,
    afetaFinanceiro: true,
    afetaEstoque: false,
    afetaLimite: true,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: true,
    geraIndicador: true,
    geraNotificacao: true,
    permiteCancelamento: false,
    permiteEstorno: true,
    exigeAutorizacao: false,
    exigeSnapshot: false
  },
  ESTORNO: {
    codigo: 'ESTORNO',
    ledger: LEDGER.CONSIGNACAO,
    afetaFinanceiro: true,
    afetaEstoque: false,
    afetaLimite: true,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: true,
    geraIndicador: true,
    geraNotificacao: true,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: true,
    exigeSnapshot: true
  },
  REABERTURA_PRESTACAO: {
    codigo: 'REABERTURA_PRESTACAO',
    ledger: LEDGER.CONSIGNACAO,
    afetaFinanceiro: false,
    afetaEstoque: false,
    afetaLimite: false,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: false,
    geraIndicador: false,
    geraNotificacao: true,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: true,
    exigeSnapshot: true
  },
  CANCELAMENTO: {
    codigo: 'CANCELAMENTO',
    ledger: LEDGER.CONSIGNACAO,
    afetaFinanceiro: false,
    afetaEstoque: true,
    afetaLimite: true,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: true,
    geraIndicador: true,
    geraNotificacao: true,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: true,
    exigeSnapshot: true
  },
  ENCERRAMENTO: {
    codigo: 'ENCERRAMENTO',
    ledger: LEDGER.CONSIGNACAO,
    afetaFinanceiro: false,
    afetaEstoque: false,
    afetaLimite: false,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: true,
    geraIndicador: true,
    geraNotificacao: false,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: false,
    exigeSnapshot: true
  },
  TRANSFERENCIA: {
    codigo: 'TRANSFERENCIA',
    ledger: LEDGER.CONSIGNACAO,
    afetaFinanceiro: false,
    afetaEstoque: false,
    afetaLimite: false,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: true,
    geraIndicador: false,
    geraNotificacao: false,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: true,
    exigeSnapshot: false
  },
  TRANSFERENCIA_SAIDA: {
    codigo: 'TRANSFERENCIA_SAIDA',
    ledger: LEDGER.CONSIGNACAO,
    afetaFinanceiro: false,
    afetaEstoque: true,
    afetaLimite: true,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: true,
    geraIndicador: false,
    geraNotificacao: false,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: true,
    exigeSnapshot: true
  },
  TRANSFERENCIA_ENTRADA: {
    codigo: 'TRANSFERENCIA_ENTRADA',
    ledger: LEDGER.CONSIGNACAO,
    afetaFinanceiro: false,
    afetaEstoque: true,
    afetaLimite: true,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: true,
    geraIndicador: false,
    geraNotificacao: false,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: true,
    exigeSnapshot: true
  },
  TERMO_ENTREGA_EMITIDO: {
    codigo: 'TERMO_ENTREGA_EMITIDO',
    ledger: LEDGER.CONSIGNACAO,
    afetaFinanceiro: false,
    afetaEstoque: false,
    afetaLimite: false,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: false,
    geraContaCorrente: false,
    geraIndicador: false,
    geraNotificacao: false,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: false,
    exigeSnapshot: true
  }
});

const TIPOS_LEDGER_PERFIL = Object.freeze({
  PERFIL_CRIADO: {
    codigo: 'PERFIL_CRIADO',
    ledger: LEDGER.PERFIL,
    afetaFinanceiro: false,
    afetaEstoque: false,
    afetaLimite: false,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: false,
    geraIndicador: true,
    geraNotificacao: false,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: false,
    exigeSnapshot: true
  },
  PERFIL_ATIVADO: {
    codigo: 'PERFIL_ATIVADO',
    ledger: LEDGER.PERFIL,
    afetaFinanceiro: false,
    afetaEstoque: false,
    afetaLimite: false,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: false,
    geraIndicador: true,
    geraNotificacao: false,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: false,
    exigeSnapshot: false
  },
  PERFIL_INATIVADO: {
    codigo: 'PERFIL_INATIVADO',
    ledger: LEDGER.PERFIL,
    afetaFinanceiro: false,
    afetaEstoque: false,
    afetaLimite: false,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: false,
    geraIndicador: true,
    geraNotificacao: true,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: true,
    exigeSnapshot: false
  },
  LIMITE_ALTERADO: {
    codigo: 'LIMITE_ALTERADO',
    ledger: LEDGER.PERFIL,
    afetaFinanceiro: false,
    afetaEstoque: false,
    afetaLimite: true,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: false,
    geraIndicador: true,
    geraNotificacao: true,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: false,
    exigeSnapshot: true
  },
  BLOQUEIO_APLICADO: {
    codigo: 'BLOQUEIO_APLICADO',
    ledger: LEDGER.PERFIL,
    afetaFinanceiro: false,
    afetaEstoque: false,
    afetaLimite: false,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: false,
    geraIndicador: true,
    geraNotificacao: true,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: false,
    exigeSnapshot: false
  },
  BLOQUEIO_REMOVIDO: {
    codigo: 'BLOQUEIO_REMOVIDO',
    ledger: LEDGER.PERFIL,
    afetaFinanceiro: false,
    afetaEstoque: false,
    afetaLimite: false,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: false,
    geraIndicador: true,
    geraNotificacao: true,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: false,
    exigeSnapshot: false
  },
  LIBERACAO_GERENCIAL: {
    codigo: 'LIBERACAO_GERENCIAL',
    ledger: LEDGER.PERFIL,
    afetaFinanceiro: false,
    afetaEstoque: false,
    afetaLimite: true,
    geraEvento: true,
    geraAuditoria: true,
    geraDashboard: true,
    geraContaCorrente: false,
    geraIndicador: true,
    geraNotificacao: true,
    permiteCancelamento: false,
    permiteEstorno: false,
    exigeAutorizacao: true,
    exigeSnapshot: true
  }
});

const CATALOGO_COMPLETO = Object.freeze({
  ...TIPOS_LEDGER_CONSIGNACAO,
  ...TIPOS_LEDGER_PERFIL
});

function obterTipoMovimentacao(codigo) {
  return CATALOGO_COMPLETO[codigo] ?? null;
}

module.exports = {
  LEDGER,
  TIPOS_LEDGER_CONSIGNACAO,
  TIPOS_LEDGER_PERFIL,
  CATALOGO_COMPLETO,
  obterTipoMovimentacao
};
